### ISSUE TITLE
CODE RUB: Correct Test Name ShouldThrowServiceExceptionOnAddIfDatabaseUpdateErrorOccursAndLogItAsync

### ISSUE THREAD

**Issue by ShriHumrudha** [cjdutoit/Glory2Him.Api#341]
https://github.com/cjdutoit/Glory2Him.Api/blob/master/G2H.Api.Web.Tests.Unit/Services/Foundations/Approvals/ApprovalServiceTests.Exceptions.Add.cs

**Comment by cjdutoit** [comment]
@ShriHumrudha what should this be changed to?

**Comment by ShriHumrudha** [comment]
> @ShriHumrudha what should this be changed to?

ShouldThrowServiceExceptionOnAddIf**Service**ErrorOccursAndLogItAsync
